"""empty message

Revision ID: 438544469d43
Revises: 9b6d3830cb2b
Create Date: 2022-07-07 23:03:28.908598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '438544469d43'
down_revision = '9b6d3830cb2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
